Add cosmology support in the galaxies pipeline
LSST-strong-lensing/sim-pipeline pull request #73
Opened 2023-09-29 16:46 UTC by trivialTZ

**Add cosmology support in the galaxies pipeline**

- Enhanced pipeline configuration to support various cosmology models.
- Ensured compatibility with the existing pipeline structure and functionality.
- Enhanced the `GalaxyGalaxyLensPop` class to accept dynamic cosmology inputs.
- Fixed issues ensuring the cosmological input directly influences galaxy generation.
@sibirrer

2023-09-29 17:15 UTC, sibirrer requested changes
Thanks a lot!
I suggest you test the cosmology that is being used is the one that you expect it to use, instead of only testing that the code runs.

Then for the formatter, you can locally run
$make format
(see make file for black and docformatter)

2023-09-29 17:15 UTC, sibirrer commented on sim_pipeline/Pipelines/skypy_pipeline.py
> +            if cosmo:
I would specify
if cosmo is not None:

2023-09-29 17:15 UTC, sibirrer commented on tests/test_Pipelines/test_skypy_pipeline.py
> +        assert blue_galaxies[0]["z"] > 0
these tests do not test whether the cosmology is overwritten. Are there other test one can do to test a specific cosmology-dependent value?

2023-09-30 17:19 UTC, trivialTZ commented
@sibirrer test for checking 'cosmology is overwritten' is on.

2023-09-30 21:59 UTC, sibirrer commented
> @sibirrer test for checking 'cosmology is overwritten' is on.

@trivialTZ I don't see the tests for using the cosmology object of the output of the pipeline result to be compared with the input of the pipeline configuration, or where can I find it?

2023-09-30 22:08 UTC, trivialTZ commented
The test between cosmology0 and cosmology1 which has two different
cosmology parameters input and the galaxies number in the output has
significant differences which indicate the change of cosmology.

Simon Birrer ***@***.***>于2023年9月30日 周六18:00写道：

> @sibirrer <https://github.com/sibirrer> test for checking 'cosmology is
> overwritten' is on.
>
> @trivialTZ <https://github.com/trivialTZ> I don't see the tests for using
> the cosmology object of the output of the pipeline result to be compared
> with the input of the pipeline configuration, or where can I find it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LSST-strong-lensing/sim-pipeline/pull/73#issuecomment-1741868498>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5IA5BHPRYMSB7DACDVH3H3X5CI6VANCNFSM6AAAAAA5MXJAVE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-30 22:11 UTC, sibirrer commented on tests/test_Pipelines/test_skypy_pipeline.py
> +        assert len(blue_galaxies) * 2 < cosmo0_blue_number
this current test does not show that the number of objects with cosmology1 is different than the one with cosmology0

2023-10-02 18:02 UTC, sibirrer approved these changes
Looks good. Thank you very much!

2023-10-02 18:03 UTC, merged